name: Web API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: "Build and Test"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure environment variables
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo ENVIRONMENT=${{ vars.ENVIRONMENT_STAGE }} >> .env

          cat .env

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test